apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poghos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/basoyan7/test-gitops.git
    targetRevision: main
    path: dev/poghos/
  destination:
    server: https://kubernetes.default.svc
    namespace: default